on:
 workflow_dispatch:

env:
  ENVIRONMENT: prod
  ENV_SECRET_NAME: AZURE_CLIENT_SECRET
  
jobs:
  installgithubcli:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Auth to GitHub CLI
        run: |
          echo "${{ secrets.GH_PAT }}" | gh auth login --with-token

      - name: Update GitHub Environment Secret
        run: |
          gh secret set ${{ env.ENV_SECRET_NAME }} \
            --env ${{ env.ENVIRONMENT }} \
            --body "AM NEW"
           echo "${{ env.ENV_SECRET_NAME }}"
          
